version: '3.7'

services:

  messenger_service:
    build: ./messenger-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./messenger-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://db_username:db_password@db/db_dev
      - AUTH_SERVICE_HOST_URL=http://auth_service:8000/api/v1/auth/
      - SENDER_SERVICE_HOST_URL=http://sender_service:8000/api/v1/sender/
    depends_on:
      - db

  auth_service:
    build: ./auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://db_username:db_password@db/db_dev
    depends_on:
      - db

  sender_service:
    build: ./sender-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./sender-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://db_username:db_password@db/db_dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - messenger_service
      - auth_service
      - sender_service

volumes:
  postgres_data_auth:
  postgres_data_messenger:
  postgres_data_sender: